FROM perl:{{version}}
MAINTAINER Rob Kinyon rob.kinyon@gmail.com

RUN apt-get update && apt-get install -y sudo

RUN curl -L http://cpanmin.us | perl - App::cpanminus
RUN cpanm \
  Carton \
  CPAN::Uploader \
  Dist::Zilla \
  Dist::Zilla::Plugin::ReadmeAnyFromPod \
  Dist::Zilla::Plugin::GitHub::Meta \
  Dist::Zilla::App::Command::cover

ENV app /app
# We need to have /app open to everyone because we don't know what user we
# will be when we run.
RUN mkdir -p $app && chmod 777 /app
WORKDIR $app

COPY "devops/MyConfig.pm" "/root/.cpan/CPAN/MyConfig.pm"
COPY "dist.ini" "/app/dist.ini"
COPY "lib" "/app/lib"

COPY "devops/within_container" "/usr/local/bin/within_container"

RUN cpanm $(dzil authordeps)
# File::Spec has a weird error that needs to be force-installed.
# It doesn't actually affect anything ... ?
RUN cpanm --force File::Spec
RUN cpanm $(dzil listdeps)

ENTRYPOINT [ "/usr/local/bin/within_container" ]
CMD [ "prove", "-lrs" ]
